# build windows build
name: Build Windows

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.1.0'
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build windows --release
      # upload artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: windows
          path: build/windows/runner/Release/*.exe