# github action for android build

name: Build Android

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.1.0'
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build apk --release
      # upload artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: android
          path: build/app/outputs/flutter-apk/app-release.apk